services:
  servicio-usuarios:
    build: ./servicios/usuarios
    container_name: soa-usuarios
    ports:
      - "8081:8081"
    networks:
      - soa-network

  servicio-ventas:
    build: ./servicios/ventas
    container_name: soa-ventas
    ports:
      - "8082:8082"
    networks:
      - soa-network

  servicio-qr:
    build: ./servicios/qr
    container_name: soa-qr
    ports:
      - "8083:8083"
    networks:
      - soa-network

  orquestador:
    build: ./orchestrator
    container_name: soa-orquestador
    ports:
      - "8080:8080"
    environment:
      - SERVICE_USUARIOS_URL=http://servicio-usuarios:8081
      - SERVICE_VENTAS_URL=http://servicio-ventas:8082
      - SERVICE_QR_URL=http://servicio-qr:8083/api
    networks:
      - soa-network

# ← ESTO ES LO QUE FALTABA
networks:
  soa-network:
    driver: bridge