server:
  port: ${PORT:8889}

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: orquestador
          uri: ${ORQUESTADOR_URL}
          predicates:
            - Path=/api/orquestador/**
          filters:
            - StripPrefix=0

        - id: auth
          uri: ${USUARIOS_URL}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: usuarios
          uri: ${USUARIOS_URL}
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - StripPrefix=0

        - id: clientes
          uri: ${CLIENTES_URL}
          predicates:
            - Path=/api/v1/clientes/**
          filters:
            - StripPrefix=0

        - id: mesas
          uri: ${MESAS_URL}
          predicates:
            - Path=/api/v1/mesas/**, /api/v1/asignaciones-mozo/**
          filters:
            - StripPrefix=0

        - id: sesiones-mesa
          uri: ${MESAS_URL}
          predicates:
            - Path=/api/v1/sesiones-mesa/**
          filters:
            - StripPrefix=0

        - id: qr
          uri: ${QR_URL}
          predicates:
            - Path=/api/v1/menu/**
          filters:
            - StripPrefix=0

        - id: ventas
          uri: ${VENTAS_URL}
          predicates:
            - Path=/api/v1/ventas/**, /api/v1/productos/**, /api/v1/pedidos/**, /api/v1/pagos/**, /api/v1/comprobantes/**
          filters:
            - StripPrefix=0

        - id: cocina
          uri: ${COCINA_URL}
          predicates:
            - Path=/api/v1/cocina/**, /api/v1/ordenes-produccion/**, /api/v1/detalles-produccion/**
          filters:
            - StripPrefix=0

        - id: inventario
          uri: ${INVENTARIO_URL}
          predicates:
            - Path=/api/v1/inventario/**
          filters:
            - StripPrefix=0

        - id: finanzas
          uri: ${FINANZAS_URL}
          predicates:
            - Path=/api/v1/finanzas/**
          filters:
            - StripPrefix=0

        - id: auditoria
          uri: ${AUDITORIA_URL}
          predicates:
            - Path=/api/v1/auditoria/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
