spring.config.import=optional:file:.env
spring.application.name=soaauditoria
server.port=8089

spring.datasource.url=jdbc:postgresql://${DB_HOST_AUDITORIA}:${DB_PORT_AUDITORIA}/${DB_NAME_AUDITORIA}
spring.datasource.username=${DB_USERNAME_AUDITORIA}
spring.datasource.password=${DB_PASSWORD_AUDITORIA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}/
