server:
  port: 7443

spring:
  application:
    name: bff
  cloud:
    gateway:
      routes:
        - id: api-gateway
          uri: ${API_GATEWAY_URL}
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
            user-name-attribute: preferred_username

  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: bff:session

  data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
