server:
  port: 8080

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: soa-orquestador
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      validation-timeout: 5000

servicios:
  usuarios:
    url: ${SERVICE_USUARIOS_URL:http://localhost:8081/api/v1}
  clientes:
    url: ${SERVICE_CLIENTES_URL:http://localhost:8082/api/v1}
  mesas:
    url: ${SERVICE_MESAS_URL:http://localhost:8083/api/v1}
  qr:
    url: ${SERVICE_QR_URL:http://localhost:8084/api/v1}
  ventas:
    url: ${SERVICE_VENTAS_URL:http://localhost:8085/api/v1}
  cocina:
    url: ${SERVICE_COCINA_URL:http://localhost:8086/api/v1}
  inventario:
    url: ${SERVICE_INVENTARIO_URL:http://localhost:8087/api/v1}
  finanzas:
    url: ${SERVICE_FINANZAS_URL:http://localhost:8088/api/v1}

logging:
  level:
    com.orquestador: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    endpoint:
      health:
        show-details: always