server:
  port: ${PORT:8080}

# app:
#   frontend-url: ${FRONTEND_URL:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: soa-orquestador
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      validation-timeout: 5000

servicios:
  usuarios:
    url: ${SERVICE_USUARIOS_URL:https://soa-back-usuarios-1.onrender.com/api/v1}
  clientes:
    url: ${SERVICE_CLIENTES_URL:https://soa-back-clientes.onrender.com/api/v1}
  mesas:
    url: ${SERVICE_MESAS_URL:https://soa-back-mesas.onrender.com/api/v1}
  qr:
    url: ${SERVICE_QR_URL:https://soa-back-qr.onrender.com/api/v1}
  ventas:
    url: ${SERVICE_VENTAS_URL:https://soa-back-ventas.onrender.com/api/v1}
  cocina:
    url: ${SERVICE_COCINA_URL:https://soa-back-cocina.onrender.com/api/v1}
  inventario:
    url: ${SERVICE_INVENTARIO_URL:https://soa-back-inventario.onrender.com/api/v1}
  finanzas:
    url: ${SERVICE_FINANZAS_URL:https://soa-back-finanzas.onrender.com/api/v1}

logging:
  level:
    com.orquestador: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    endpoint:
      health:
        show-details: always